name: release
on:
  push:
    tags: '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm charts
        uses: min-charles/helm-charts@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
